import {
  BACKGROUND_GREY,
  LIGHT_PLACEHOLDER,
  PALE_YELLOW,
  PRIMARY_BLACK,
  TEXT_BLACK,
  WHITE,
  ROOT_BLUE,
  LINK_BLUE,
} from "../../../Constants/color";
import {
  FONT_FAMILY_LARSSEIT,
  FONT_FAMILY_METROPOLIS,
  FONT_FAMILY_NUNITO_SANS,
  FONT_FAMILY_INTER,
} from "../../../Assests/Styles/commonStyles";
import { commonStyles } from "../../../Assests/Styles/commonStyles";

export const styles = {
  tableMainContainer: {
    backgroundColor: WHITE,
    boxShadow: "none",
    overflow: "auto",
  },
  badge: {
    "& .MuiBadge-badge": {
      right: 1,
      top: 5,
      padding: "0 4px",
    },
  },
  headingText: {
    fontFamily: FONT_FAMILY_METROPOLIS,
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "12px",
    lineHeight: "20px",
    color: TEXT_BLACK,
    backgroundColor: "rgba(8, 9, 64, 0.09)",
    textTransform: "lowercase",
    "&::first-letter": {
      textTransform: "capitalize",
    },
  },
  emptyIcon: { marginTop: "20px" },
  emptyMessage: { color: "rgb(164, 184, 214)", marginTop: "10px" },
  tableWrapper: {
    paddingTop: "50px",
    paddingBottom: "20px",
    paddingLeft: "20px",
    paddingRight: "20px",
    backgroundColor: WHITE,
    marginTop: "34px",
    boxShadow: "0px 15px 44px rgba(0, 0, 0, 0.07)",
    borderRadius: "16px",
    minHeight: "calc(100vh - 350px)",
  },
  tableMainWrapper: {
    marginLeft: "20px",
    marginRight: "20px",
    marginTop: "53px",
    display: "flex",
    flexDirection: "column",
  },
  tableRowContainer: {
    maxHeight: "calc(100vh - 430px)",
    width: "calc(100% - 15px)",
    margin: "auto",
    marginTop: "8px",
    "@media(max-height: 400px)": {
      maxHeight: "200px",
    },
  },
  tablePagination: {
    ".MuiTablePagination-actions": {
      button: {
        display: "none",
      },
    },
    ".MuiTablePagination-select": {
      fontFamily: FONT_FAMILY_METROPOLIS,
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "12px",
      lineHeight: "12px",
      color: TEXT_BLACK,
      border: "1px solid rgba(20, 20, 20, 0.29)",
      borderRadius: "4px",
      minWidth: "53px",
      minHeight: "23px",
      boxSizing: "border-box",
      "&:focus": {
        border: "1px solid rgba(20, 20, 20, 0.29)",
        borderRadius: "4px",
      },
    },
    ".MuiTablePagination-displayedRows": {
      fontFamily: FONT_FAMILY_METROPOLIS,
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "12px",
      lineHeight: "12px",
      color: TEXT_BLACK,
    },
  },
  pagination: {
    "& .MuiPaginationItem-root": {
      "&.Mui-selected": {
        background: PALE_YELLOW,
      },
      backgroundColor: WHITE,
      fontFamily: FONT_FAMILY_NUNITO_SANS,
      fontStyle: "normal",
      fontWeight: 700,
      fontSize: "12px",
      lineHeight: "16px",
      color: TEXT_BLACK,
      mixBlendMode: "normal",
    },
    flexGrow: 1,
    display: "flex",
    justifyContent: "center",
  },
  actionItemContainer: {
    display: "flex",
    alignItems: "center",
    columnGap: "20px",
  },
  searchbarContainer: { flexGrow: "1" },
  paginationContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "70px",
  },
  tableContainer: {
    ".MuiTableRow-root": {
      th: {
        borderBottom: "none",
        paddingLeft: "9px",
        paddingRight: "12px",
      },
      "th:first-of-type": {
        borderTopLeftRadius: "8px",
        borderBottomLeftRadius: "8px",
        borderBottom: "none",
        textTransform: "lowercase",
        padding: "10px 20px",
        paddingLeft: "25px !important",
      },
      "th:last-child": {
        borderTopRightRadius: "8px",
        borderBottomRightRadius: "8px",
        borderBottom: "none",
        textTransform: "lowercase",
        padding: "10px 0px",
      },
      td: {
        padding: "12px",
        borderBottom: "none",
        zIndex: "1300",
      },
    },
  },
  tableHeadRow: {
    zIndex: "1300",
  },
  itemNormalText: {
    fontFamily: FONT_FAMILY_METROPOLIS,
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "20px",
    color: TEXT_BLACK,
    width: "100%",
    wordBreak: "break-word",
  },
  itemTextName: {
    overflow: "hidden",
    maxWidth: "100px",
    textOverflow: "ellipsis",
    wordBreak: "auto",
    maxHeight: "22px",
  },
  itemClickableText: {
    cursor: "pointer",
  },
  linkItem: {
    textDecoration: "underline",
    color: LINK_BLUE,
    fontWeight: 600,
    cursor: "pointer",
  },
  mainRows: {
    background: WHITE,
    boxShadow: "inset 0px -1px 1px rgba(0, 0, 0, 0.16)",
    position: "relative",
  },
  presentation: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "200px",
  },
  heading: {
    fontFamily: FONT_FAMILY_LARSSEIT,
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "26px",
    lineHeight: "26px",
    color: TEXT_BLACK,
  },
  actionButton: {
    fontFamily: FONT_FAMILY_METROPOLIS,
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "14px",
    lineHeight: "14px",
    color: TEXT_BLACK,
    borderRadius: "4px",
    padding: "14px 15px",
    height: "40px",
  },
  topContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: "60px",
  },
  tabMainContainer: {
    display: "flex",
    alignItems: "flex-end",
  },
  tabsContainer: {
    backgroundColor: TEXT_BLACK,
  },
  tabStyle: {
    paddingTop: "0",
    paddingBottom: "0",
  },
  inActiveTabStyle: {
    fontFamily: FONT_FAMILY_LARSSEIT,
    fontSize: "18px",
    lineHeight: "18px",
    fontWeight: "500",
    color: `${TEXT_BLACK} !important`,
  },
  activeTabStyle: {
    fontFamily: FONT_FAMILY_LARSSEIT,
    fontSize: "20px",
    lineHeight: "20px",
    fontWeight: "700",
    color: `${TEXT_BLACK} !important`,
  },
  editIconBox: {
    display: "flex",
    justifyContent: "flex-end",
    marginRight: "10px",
  },
  iconContainer: {
    display: "flex",
    justifyContent: "flex-start",
  },
  chatIconBox: {
    display: "flex",
    justifyContent: "start",
    marginRight: "10px",
  },
  editIcon: {
    cursor: "pointer",
  },
  imageStyle: {
    maxWidth: "125px",
    maxHeight: "72px",
    borderRadius: "0px",
    objectFit: "cover",
  },
  collapseTextStyle: {
    display: "flex",
    justifyContent: "flex-end",
    marginRight: "20px",
    textDecoration: "underline",
    textDecorationColor: "rgba(20, 20, 20, 0.11)",
  },
  containerWrapper: {
    background: BACKGROUND_GREY,
    border: `1px solid ${LIGHT_PLACEHOLDER}`,
    borderRadius: "6px",
    padding: "4px 8px",
    width: "fit-content",
    p: {
      fontFamily: FONT_FAMILY_METROPOLIS,
      fontStyle: "normal",
      fontWeight: 500,
      fontSize: "12px",
      lineHeight: "20px",
      color: PRIMARY_BLACK,
      wordBreak: "break-all",
    },
  },
  boldPrice: {
    fontWeight: 700,
    color: PRIMARY_BLACK,
  },
  outerScrollStyle: {
    overflow: "auto",
    width: { md: "calc(100vw - 350px)", sm: "auto", xl: "auto" },
    paddingBottom: "10px",
    ...commonStyles.scrollBar,
  },
  innerScrollStyle: {
    width: "1300px",
    "@media(min-width: 1400px)": {
      width: "auto",
    },
  },
  noslotsBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "140px",
  },
  noSlotsAvailableStyle: {
    fontFamily: FONT_FAMILY_METROPOLIS,
    fontSize: "20px",
    lineHeight: "24px",
    fontWeight: "700",
    color: ROOT_BLUE,
  },
  timeChip: {
    background: BACKGROUND_GREY,
    border: `1px solid ${LIGHT_PLACEHOLDER}`,
    borderRadius: "6px",
    color: TEXT_BLACK,
    fontSize: "12px",
    fontWeight: 500,
    marginBottom: "10px",
  },
  dateText: {
    fontWeight: 500,
    fontSize: "14px",
    color: TEXT_BLACK,
  },
  dateTimeWrap: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  customSelectBox: {
    ".MuiSelect-select": {
      paddingTop: "7px",
      paddingBottom: "4px",
      border: `1px solid ${ROOT_BLUE}`,
      borderRadius: "6px",
      "> p": {
        fontSize: "12px",
        fontFamily: FONT_FAMILY_METROPOLIS,
        fontWeight: 500,
        color: ROOT_BLUE,
      },
    },
    ".MuiInputBase-input": {
      borderRadius: "6px",
      "&:focus": {
        borderRadius: "6px",
      },
    },
    ".MuiSvgIcon-root": {
      color: ROOT_BLUE,
    },
  },
  disabledStyle: {
    ".Mui-disabled": {
      border: `1px solid ${BACKGROUND_GREY}`,
      backgroundColor: LIGHT_PLACEHOLDER,
      paddingTop: "7px",
      paddingBottom: "4px",
      borderRadius: "6px",
      "> p": {
        fontSize: "12px",
        fontFamily: FONT_FAMILY_METROPOLIS,
        fontWeight: 700,
        color: `${TEXT_BLACK} !important`,
      },
    },
    ".MuiSvgIcon-root": {
      display: "none",
    },
  },
  textMenuWrap: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  textMenuText: {
    fontFamily: FONT_FAMILY_METROPOLIS,
    fontWeight: 700,
    fontSize: "14px",
    color: TEXT_BLACK,
  },
  customSelectBoxWrap: {
    "@media (min-width: 1800px)": {
      maxWidth: "70%",
    },
  },
  customSelectBoxStyle: {
    display: "flex",
    minWidth: "220px",
    maxWidth: "220px",
  },
  descriptionText: {
    fontFamily: FONT_FAMILY_METROPOLIS,
    fontSize: "18px",
    lineHeight: "23px",
    fontWeight: "700",
    color: TEXT_BLACK,
  },
  detailDifferentiatorArrayWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "end",
    columnGap: "23px",
    marginBottom: "15px",
    marginRight: "10px",
    "@media(max-width: 1400px)": {
      marginRight: "30px",
    },
  },
  cellStyle: {
    position: "relative",
  },
  circleIconPosition: {
    position: "absolute",
    top: "50%",
    transform: "translate(0, -50%)",
  },
  differentiatorDetail: {
    fontFamily: FONT_FAMILY_INTER,
    fontSize: "14px",
    lineHeight: "17px",
    fontWeight: "500",
    letterSpacing: "-0.333333px",
    color: PRIMARY_BLACK,
  },
  assignmentName: {
    fontFamily: FONT_FAMILY_METROPOLIS,
    fontSize: "14px",
    lineHeight: "20px",
    fontWeight: "500",
    color: PRIMARY_BLACK,
  },
  assignmentNameMatched: {
    color: ROOT_BLUE,
    fontWeight: "700",
  },
  assignmentStyle: {
    display: "flex",
    alignItems: "center",
    columnGap: "5px",
  },
  tableCellCollapse: { paddingBottom: 0, paddingTop: 0 },
  sortingIcons: {
    cursor: "pointer",
    fontSize: "14px !important",
    marginLeft: "5px",
  },
  enableSortHeadingContainer: {
    display: "flex",
    alignItems: "center",
    textTransform: "none",
  },
  doubleArrow: { height: "12px", width: "12px", marginLeft: "10px" },
  newTag: {
    position: "absolute",
    top: "11px",
    backgroundColor: PALE_YELLOW,
    borderRadius: "5px",
    width: "40px",
    textAlign: "center",
    fontWeight: 600,
    fontSize: "12px",
  },
  inactiveHeaderNavigation: {
    cursor: "pointer",
    color: ROOT_BLUE,
  },
};
